# Generated by Django 4.1.1 on 2022-09-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_exam_soal'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='modat_zaman',
            field=models.CharField(default='10 دقیقه', max_length=1000),
        ),
        migrations.AddField(
            model_name='exam',
            name='time',
            field=models.TimeField(default='10'),
            preserve_default=False,
        ),
    ]
